language: python
python:
  - "2.7"
before_install:
  - pip install codecov
install:
  - pip install -r requirements.txt
script:
  - python manage.py makemigrations
  - python manage.py test pttrack
after_success:
  - codecov