version: "3"
services:
  web:
    container_name: osler_app
    build:
      context: .
      dockerfile: Dockerfile
    image: osler
    stop_signal: SIGINT
    stdin_open: true
    tty: true
    volumes:
      - .:/osler
    networks:
      - nginx_network
      - database_network
    depends_on:
      - db
    environment:
      DJANGO_SETTINGS_MODULE: osler.docker_settings
      DJANGO_SECRET_KEY: 7^9cf-1d#z2j#@t0-vo2=l7e7z=n@g8_na56c_(pwbx8dnk3)l
      DATABASE_BACKEND: django.db.backends.postgresql_psycopg2
      DATABASE_PASSWORD: debug-password
      DATABASE_NAME: osler
      DATABASE_USER: django
      DATABASE_PORT: 5432
      DATABASE_HOST: db
  db:
    container_name: osler_db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: osler
      POSTGRES_PASSWORD: debug-password
      POSTGRES_USER: django
    networks:
      - database_network
  nginx:
    image: nginx:latest
    container_name: nginx_server
    restart: always
    ports:
      # - "0.0.0.0:80:80"
      # - "0.0.0.0:80:80"
      - 8000:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge
  database_network:  # <-- add the bridge
    driver: bridge
