version: '3.8'

services:
  docs:
    image: osler_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./osler:/app/osler:z
    ports:
      - "7000:7000"
    command: /start-docs
