version: '3.8'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: osler_local_django
    container_name: django
    depends_on:
      - postgres
      - selenium
    volumes:
      - .:/app
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    command: /start
    networks:
      - selenium_network
      - database_network
      - nginx_network

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: osler_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data
      - local_postgres_data_backups:/backups
    env_file:
      - ./.envs/.local/.postgres
    networks:
      - database_network

  nginx:
    image: nginx:1.19
    container_name: nginx
    ports:
      - 8000:8000
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8000
      - NGINX_REVERSE_PROXY=django:8000
    volumes:
      - ./compose/local/nginx/templates:/etc/nginx/templates
    depends_on:
      - django
    networks:
      - nginx_network

  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug:3.141
    ports:
      - 4444:4444   # Selenium
      - 5900:5900   # VNC server
    networks:
      - selenium_network

  docs:
    image: osler_local_docs
    container_name: docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./osler:/app/osler:z
    ports:
      - "7000:7000"
    command: /start-docs

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge
  selenium_network:
    driver: bridge
