version: '3'

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}

networks:
  default:
    driver: bridge
    driver_opts:
      # this MTU size should be the same as the host network
      # check with `ifconfig | grep -i mtu` on host & vm
      com.docker.network.driver.mtu: 1500

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: osler_production_django
    depends_on:
      # - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.secrets
      - ./.envs/.production/.umkc
    command: /start
    ports:
      - "5000:5000"
    extra_hosts:
      - "kc-med-oslerdb.kc.umkc.edu:192.168.0.2"

  redis:
    image: redis:5.0
