version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_static_files: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: osler_production_django
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
      - ./.envs/.production/.secrets
    command: /start
    # ports:
    #   - 5000:5000
    expose:
      - 5000
    volumes:
      - production_static_files:/app/staticfiles

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: osler_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.secrets

  nginx:
    build: ./compose/production/nginx
    ports:
      - 1337:80
    depends_on:
      - django
    volumes:
      - production_static_files:/app/static

  redis:
    image: redis:5.0
