version: "3"

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_static_files: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: llemr_production_django
    depends_on:
      - postgres
      - redis
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings.demo
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.secrets
    command: /start
    volumes:
      - production_static_files:/app/staticfiles
    networks:
      - nginx_network
      - database_network

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: llemr_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.secrets
    networks:
      - database_network

  nginx:
    build: ./compose/production/nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - django
    volumes:
      - production_static_files:/app/staticfiles
    networks:
      - nginx_network

  redis:
    image: redis:5.0

networks:
  nginx_network:
    driver: bridge
  database_network:
    driver: bridge